server:
  port: 8083


spring:
  datasource:
    url: jdbc:mariadb://49.50.173.86:3306/everyparking
    username: root
    password: dd990219
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/everyparking?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#    username: wans
#    password: chltmdghks6245
#    driver-class-name: org.mariadb.jdbc.Driver



  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace


file:
  dir: /root/server/server/file/

#file:
#  dir: /home/ubuntu/history/